// Auto-generated from 中考词汇 PDFs. Do not edit manually.
export interface VocabWord { word: string; meaning: string }
export interface VocabGroup { id: number; name: string; words: VocabWord[] }

export const VOCAB_GROUPS: VocabGroup[] = [
  { id: 1, name: "第1组", words: [
    { word: "increase", meaning: "增长，增加 v" },
    { word: "director", meaning: "导演，主任 n" },
    { word: "encourage", meaning: "鼓励 v" },
    { word: "astronaut", meaning: "宇航员 n" },
    { word: "calm", meaning: "冷静 v adj" },
    { word: "adulthood", meaning: "成年 n" },
    { word: "various", meaning: "各种各样的 adj" },
    { word: "conclude", meaning: "做结论、以…为结束 v" },
    { word: "author", meaning: "作者 n" },
    { word: "mood", meaning: "心情 n" },
    { word: "ashamed", meaning: "羞愧 adj" },
    { word: "take after", meaning: "和...长得像" },
    { word: "survey", meaning: "调查 v n" },
    { word: "tell", meaning: "区分 v" },
    { word: "contain", meaning: "包含 v" },
    { word: "produce", meaning: "生产 v" },
    { word: "practical", meaning: "实用的 adj" },
    { word: "significant", meaning: "重要的 adj" },
    { word: "locate", meaning: "位于 v" },
    { word: "survive", meaning: "幸存 v" },
  ]},
  { id: 2, name: "第2组", words: [
    { word: "doubt", meaning: "怀疑 v n" },
    { word: "in order to", meaning: "为了" },
    { word: "crisis", meaning: "危机 n" },
    { word: "land the job", meaning: "得到工作" },
    { word: "attendance", meaning: "出席 n" },
    { word: "drop", meaning: "掉落 v；雨滴 n" },
    { word: "imagination", meaning: "想象力 n" },
    { word: "breathe", meaning: "呼吸 v" },
    { word: "puzzled", meaning: "困惑的 adj" },
    { word: "attempt", meaning: "尝试 n v" },
    { word: "experiment", meaning: "实验 n v" },
    { word: "cancel", meaning: "取消 v" },
    { word: "facial", meaning: "面部的 adj" },
    { word: "inefficient", meaning: "没有效率的 adj" },
    { word: "accept", meaning: "接受 v" },
    { word: "be responsible for", meaning: "对...负责" },
    { word: "charity", meaning: "慈善 n" },
    { word: "enable", meaning: "使能够 v" },
    { word: "turn to", meaning: "求助，转向" },
    { word: "disease", meaning: "疾病 n" },
  ]},
  { id: 3, name: "第3组", words: [
    { word: "sensitive", meaning: "敏感的 adj" },
    { word: "stare", meaning: "瞪着 v" },
    { word: "take part in", meaning: "参加" },
    { word: "hopeful", meaning: "有希望的 adj" },
    { word: "chain", meaning: "链条 n" },
    { word: "coach", meaning: "教练 n v" },
    { word: "you have my words", meaning: "我对你承诺；我答应你" },
    { word: "conversation", meaning: "对话 n" },
    { word: "whisper", meaning: "低声说 v" },
    { word: "ruin", meaning: "毁灭 v 废墟 n" },
    { word: "feel", meaning: "感觉 v" },
    { word: "as", meaning: "因为，当，就像，作为 conj" },
    { word: "strategy", meaning: "策略 n" },
    { word: "fail to do", meaning: "失败" },
    { word: "finalist", meaning: "参加决赛者 n" },
    { word: "make through", meaning: "渡过难关了" },
    { word: "strengthen", meaning: "增强力量 v." },
    { word: "specific", meaning: "详细的，特定的 adj" },
    { word: "schedule", meaning: "日程安排 n" },
    { word: "appear", meaning: "出现 v" },
  ]},
  { id: 4, name: "第4组", words: [
    { word: "hardly", meaning: "几乎不 adv" },
    { word: "tough", meaning: "艰难的 adj" },
    { word: "treasure", meaning: "宝藏 n" },
    { word: "weakness", meaning: "弱点 n" },
    { word: "rate", meaning: "率 n" },
    { word: "donate", meaning: "捐献 v" },
    { word: "World War I", meaning: "第一次世界大战" },
    { word: "smelly", meaning: "难闻的 adj" },
    { word: "participate", meaning: "参与 v" },
    { word: "attract", meaning: "吸引 v" },
    { word: "realize", meaning: "意识到；实现 v" },
    { word: "side effect", meaning: "副作用 n" },
    { word: "protect", meaning: "保护 v" },
    { word: "inattentive", meaning: "注意力不集中的 adj" },
    { word: "topic", meaning: "话题 n" },
    { word: "wonder", meaning: "想知道，琢磨 v" },
    { word: "quality", meaning: "质量 n" },
    { word: "employee", meaning: "雇员 n" },
    { word: "disgusting", meaning: "恶心的 adj" },
    { word: "draw attention", meaning: "吸引注意力" },
  ]},
  { id: 5, name: "第5组", words: [
    { word: "lifelike", meaning: "adj" },
    { word: "theory", meaning: "理论 n" },
    { word: "relief", meaning: "缓解 n." },
    { word: "save", meaning: "存下，节省；救命 v" },
    { word: "take note", meaning: "记笔记" },
    { word: "at least", meaning: "至少" },
    { word: "cheat", meaning: "欺骗 v" },
    { word: "do one's best to do sth", meaning: "尽某人最大努力做某事" },
    { word: "personality", meaning: "个性 n" },
    { word: "carry out", meaning: "实施" },
    { word: "necessary", meaning: "有必要的 adj" },
    { word: "enough", meaning: "足够 adj" },
    { word: "elect", meaning: "选举 v" },
    { word: "beneficial", meaning: "有益的 adj" },
    { word: "land", meaning: "着陆 v ；陆地 n" },
    { word: "discovery", meaning: "发现 n" },
    { word: "prove", meaning: "证明，证实 v" },
    { word: "scary", meaning: "可怕的 adj" },
    { word: "application", meaning: "申请 n" },
    { word: "post", meaning: "邮递，投放 v" },
  ]},
  { id: 6, name: "第6组", words: [
    { word: "organization", meaning: "组织 n" },
    { word: "public", meaning: "公共的 adj" },
    { word: "social", meaning: "社交的 adj" },
    { word: "refer to", meaning: "参考，涉及，适用于" },
    { word: "draw", meaning: "吸引，拉，拖；画 v" },
    { word: "article", meaning: "文章，小物件 n" },
    { word: "meet", meaning: "迎合 v" },
    { word: "take place", meaning: "发生" },
    { word: "talent show", meaning: "才艺表演" },
    { word: "quarrel", meaning: "争吵 v" },
    { word: "transport", meaning: "交通 n" },
    { word: "wisdom", meaning: "智慧 n" },
    { word: "distance", meaning: "距离 n" },
    { word: "direction", meaning: "方向 n" },
    { word: "tear", meaning: "n. 眼泪； v. 撕" },
    { word: "research", meaning: "研究 v n" },
    { word: "favorable", meaning: "收到喜爱的 adj" },
    { word: "instruct", meaning: "指导 v" },
    { word: "active", meaning: "活跃的，积极的 adj" },
    { word: "show off", meaning: "炫耀" },
  ]},
  { id: 7, name: "第7组", words: [
    { word: "include", meaning: "包括，包含 v" },
    { word: "tool", meaning: "工具 n" },
    { word: "figure out", meaning: "弄明白" },
    { word: "addict", meaning: "上瘾的 adj" },
    { word: "be tired of", meaning: "厌烦 …" },
    { word: "take off", meaning: "（飞机）起飞；脱下（衣服）" },
    { word: "study", meaning: "研究，学习 v；书房 n" },
    { word: "happy", meaning: "快乐（名词）" },
    { word: "material", meaning: "材料 n" },
    { word: "fairness", meaning: "公平 n（ness是名词后缀）" },
    { word: "attention", meaning: "注意，注意力 n" },
    { word: "unfortunately", meaning: "不幸地 adv" },
    { word: "draw back", meaning: "退却，收回" },
    { word: "standard", meaning: "标准 n" },
    { word: "blow out", meaning: "吹灭" },
    { word: "release", meaning: "释放 v" },
    { word: "efficient", meaning: "高效的 adj" },
    { word: "pass", meaning: "递给；通过 v" },
    { word: "mark", meaning: "分数；标记 v n" },
    { word: "recent", meaning: "最近的 adj" },
  ]},
  { id: 8, name: "第8组", words: [
    { word: "make a big decision", meaning: "决定做某事" },
    { word: "sell out", meaning: "卖光了" },
    { word: "explain", meaning: "解释 v" },
    { word: "equally", meaning: "公平地 adv" },
    { word: "familiar", meaning: "熟悉的 adj" },
    { word: "embarrassed", meaning: "尴尬 adj" },
    { word: "plant", meaning: "种植 v 植物 n" },
    { word: "background", meaning: "背景 n" },
    { word: "consumer", meaning: "消费者 n" },
    { word: "be/get used to doing", meaning: "习惯做某事" },
    { word: "anxious", meaning: "焦虑的 adj" },
    { word: "silly", meaning: "愚蠢的 adj" },
    { word: "healthcare", meaning: "健康护理 n" },
    { word: "award", meaning: "颁奖 v 奖 n" },
    { word: "a symbol of", meaning: "…的象征" },
    { word: "condition", meaning: "条件 n" },
    { word: "be eager to do", meaning: "渴望做某事" },
    { word: "harm", meaning: "受伤 v n" },
    { word: "brave", meaning: "勇敢的 adj；" },
    { word: "honor", meaning: "荣誉 n" },
  ]},
  { id: 9, name: "第9组", words: [
    { word: "discourage", meaning: "使...泄气 v" },
    { word: "reminder", meaning: "提醒 n" },
    { word: "combine", meaning: "连接 v" },
    { word: "anxiety", meaning: "焦虑 n" },
    { word: "concern", meaning: "担心 n" },
    { word: "long for", meaning: "渴望 v" },
    { word: "ahead", meaning: "在前面，领先 adv" },
    { word: "diet", meaning: "饮食 n" },
    { word: "task", meaning: "任务 n" },
    { word: "journey", meaning: "旅行 n" },
    { word: "rest", meaning: "剩余的东西 n adj" },
    { word: "character", meaning: "品格、角色、汉字 n" },
    { word: "assist", meaning: "辅助 v" },
    { word: "experience", meaning: "经验；经历，体验 n" },
    { word: "self-taught", meaning: "自学" },
    { word: "as a result", meaning: "作为结果、结果" },
    { word: "shape", meaning: "形状 n" },
    { word: "enter", meaning: "进入 v" },
    { word: "properly", meaning: "恰当地 adv" },
    { word: "fix", meaning: "修理，固定，凝视 v" },
  ]},
  { id: 10, name: "第10组", words: [
    { word: "digital", meaning: "数码的，数字的 adj" },
    { word: "discover", meaning: "发现 v" },
    { word: "object", meaning: "物体 n" },
    { word: "involve", meaning: "涉及，卷入 v" },
    { word: "similar", meaning: "相似的 adj" },
    { word: "create", meaning: "创造 v" },
    { word: "be known for", meaning: "出名，因…而众所周知" },
    { word: "disappoint", meaning: "使...失望 v" },
    { word: "activity", meaning: "活动 n" },
    { word: "totally", meaning: "完全地 adv" },
    { word: "trustworthy", meaning: "值得相信的 adj" },
    { word: "connect", meaning: "连接 v" },
    { word: "be used to doing sth", meaning: "习惯于做某事" },
    { word: "lie", meaning: "躺 v" },
    { word: "enrich", meaning: "使丰富 v" },
    { word: "medal", meaning: "奖牌 n" },
    { word: "respond", meaning: "反应 v" },
    { word: "in public", meaning: "公众" },
    { word: "discuss", meaning: "讨论 v" },
    { word: "alone", meaning: "孤单的 adj" },
  ]},
  { id: 11, name: "第11组", words: [
    { word: "amount", meaning: "数量 n" },
    { word: "risk", meaning: "险）" },
    { word: "little", meaning: "少-更少-最少 adj" },
    { word: "positive", meaning: "积极的；阳性的 adj" },
    { word: "in debt", meaning: "负债" },
    { word: "appearance", meaning: "外貌 n" },
    { word: "mislead-misled", meaning: "误导 v" },
    { word: "be likely to do", meaning: "很可能怎么样" },
    { word: "overcome", meaning: "克服 v" },
    { word: "shy", meaning: "害羞 adj" },
    { word: "tradition", meaning: "传统 n" },
    { word: "speed", meaning: "加速 v" },
    { word: "influence", meaning: "影响 v n" },
    { word: "book", meaning: "预定 v" },
    { word: "however", meaning: "然而 adv conj" },
    { word: "in order", meaning: "按顺序" },
    { word: "unwilling", meaning: "不愿意 adj" },
    { word: "valuable", meaning: "有价值的 adj" },
    { word: "nervous", meaning: "紧张的 adj" },
    { word: "weather", meaning: "天气" },
  ]},
  { id: 12, name: "第12组", words: [
    { word: "trust", meaning: "相信 v" },
    { word: "be full of", meaning: "充满" },
    { word: "impolite", meaning: "没礼貌的 adj" },
    { word: "local", meaning: "当地的 adj" },
    { word: "discussion", meaning: "讨论 n" },
    { word: "defense", meaning: "防御 n 抵御 v" },
    { word: "athletic", meaning: "运动的 adj" },
    { word: "similarity", meaning: "相似性 n" },
    { word: "workload", meaning: "工作量 n" },
    { word: "design", meaning: "设计 v n" },
    { word: "consider", meaning: "考虑 v" },
    { word: "direct", meaning: "直接的；管理，指挥 v" },
    { word: "program", meaning: "节目 n" },
    { word: "the number of", meaning: "…的数量" },
    { word: "breakout", meaning: "爆发 n" },
    { word: "dependence", meaning: "依赖 n" },
    { word: "can't wait to do sth", meaning: "迫不及待做某事" },
    { word: "tight", meaning: "紧的 adj" },
    { word: "compete", meaning: "竞争 v" },
    { word: "improve", meaning: "提高，改善 v" },
  ]},
  { id: 13, name: "第13组", words: [
    { word: "calendar", meaning: "日历 n" },
    { word: "curious", meaning: "好奇的 adj" },
    { word: "recently", meaning: "最近地 adv" },
    { word: "explore", meaning: "探险，探索 v" },
    { word: "take in", meaning: "吸收" },
    { word: "unworthy", meaning: "不值得 adj" },
    { word: "strength", meaning: "力量 n." },
    { word: "make sense", meaning: "讲得通，言之有理" },
    { word: "expose", meaning: "暴露，接触 v" },
    { word: "link", meaning: "链接 n ；连接 v" },
    { word: "expert", meaning: "专家 n" },
    { word: "promise", meaning: "承诺 v n" },
    { word: "actually", meaning: "实际上 adv" },
    { word: "used to do", meaning: "过去常常做某事" },
    { word: "stressful", meaning: "有压力的 adj" },
    { word: "involved", meaning: "涉及的，卷入的 adj" },
    { word: "pollution", meaning: "污染 n" },
    { word: "bet", meaning: "打赌 v" },
    { word: "access", meaning: "获取 v n" },
    { word: "ask sb for", meaning: "向某人要..." },
  ]},
  { id: 14, name: "第14组", words: [
    { word: "overwhelm", meaning: "淹没、压倒、盖过 v" },
    { word: "confuse", meaning: "使...困惑 v" },
    { word: "routine", meaning: "惯例 n" },
    { word: "raise", meaning: "举起、养育、筹钱 v" },
    { word: "stand for", meaning: "代表" },
    { word: "against", meaning: "反对 prep" },
    { word: "speech", meaning: "演讲 n" },
    { word: "fit", meaning: "适合的，健康的 adj" },
    { word: "scream", meaning: "尖叫 v" },
    { word: "again", meaning: "再一次，又 adv" },
    { word: "weapon", meaning: "兵器，武器 n" },
    { word: "neat", meaning: "整齐的，整洁的 adj" },
    { word: "unchangeable", meaning: "不会改变的 adj" },
    { word: "roll", meaning: "滚动 v；卷 n" },
    { word: "disorganized", meaning: "没组织的，混乱的 adj" },
    { word: "inattentiveness", meaning: "走神，不关注 n" },
    { word: "inexpensive", meaning: "不贵的 adj" },
    { word: "nod", meaning: "点头 v" },
    { word: "order", meaning: "订购，点菜，命令 v;顺序 n" },
    { word: "fill", meaning: "填写 v" },
  ]},
  { id: 15, name: "第15组", words: [
    { word: "stress", meaning: "压力 n；强调 v" },
    { word: "to my surprise", meaning: "令我吃惊的是" },
    { word: "while", meaning: "然而 conj" },
    { word: "invitation", meaning: "邀请函 n" },
    { word: "negative", meaning: "消极的 adj" },
    { word: "prevent", meaning: "阻止 v" },
    { word: "exposure", meaning: "暴露，接触 n" },
    { word: "behavior", meaning: "行为 n" },
    { word: "objective", meaning: "客观的 adj 目标 n" },
    { word: "advertisement", meaning: "广告 n" },
    { word: "train", meaning: "训练 v" },
    { word: "once", meaning: "一次 adv，曾经，一旦 conj" },
    { word: "vehicle", meaning: "交通工具 n" },
    { word: "solve", meaning: "解决 v" },
    { word: "dislike", meaning: "不喜欢 v" },
    { word: "data", meaning: "数据 n" },
    { word: "aware", meaning: "意识到的 adj" },
    { word: "proof", meaning: "证据 n" },
    { word: "even", meaning: "甚至 adv" },
    { word: "structure", meaning: "结构 n" },
  ]},
  { id: 16, name: "第16组", words: [
    { word: "factor", meaning: "因素 n" },
    { word: "devote to", meaning: "奉献 v" },
    { word: "destroy", meaning: "毁坏 v" },
    { word: "decorate", meaning: "装饰 v" },
    { word: "be stuck", meaning: "卡住" },
    { word: "amuse", meaning: "逗乐 v" },
    { word: "apply to", meaning: "适用于" },
    { word: "depend on", meaning: "依靠，依赖" },
    { word: "avoid doing sth", meaning: "避免 v" },
    { word: "perform task", meaning: "执行任务" },
    { word: "polite", meaning: "有礼貌的 adj" },
    { word: "quite", meaning: "十分，很 adv" },
    { word: "situation", meaning: "情境 n" },
    { word: "improper", meaning: "不适当的 adj" },
    { word: "interact", meaning: "互动 v" },
    { word: "bear", meaning: "容忍 v" },
    { word: "personal", meaning: "个人的 adj" },
    { word: "comfort", meaning: "安慰 v" },
    { word: "lonely", meaning: "孤独的 adj" },
    { word: "advanced", meaning: "高级的 adj" },
  ]},
  { id: 17, name: "第17组", words: [
    { word: "sentence", meaning: "句子 n" },
    { word: "damage", meaning: "损伤 v n" },
    { word: "sign", meaning: "签字 v；牌子，符号，手势 n" },
    { word: "smells", meaning: "不好闻的气味 n" },
    { word: "can't help doing", meaning: "情不自禁做某事" },
    { word: "add", meaning: "添加 v" },
    { word: "victory", meaning: "胜利 n" },
    { word: "react", meaning: "反应 v" },
    { word: "variety", meaning: "各种各样 n" },
    { word: "provide", meaning: "提供 v" },
    { word: "instead of", meaning: "而不是，代替" },
    { word: "responsibility", meaning: "责任 n" },
    { word: "possibility", meaning: "可能性 n" },
    { word: "show up", meaning: "出现 v" },
    { word: "I was told", meaning: "我被告知" },
    { word: "effort", meaning: "努力 n" },
    { word: "decade", meaning: "十年 n" },
    { word: "sense", meaning: "感觉 v n" },
    { word: "announce", meaning: "宣布 v" },
    { word: "deserve", meaning: "值得 v" },
  ]},
  { id: 18, name: "第18组", words: [
    { word: "nutrition", meaning: "营养 n" },
    { word: "take up", meaning: "占据" },
    { word: "apply", meaning: "申请 v" },
    { word: "project", meaning: "项目 n" },
    { word: "concentrate", meaning: "聚精会神 v" },
    { word: "directly", meaning: "直接地 adv" },
    { word: "deal with", meaning: "处理" },
    { word: "pressure", meaning: "压力 n" },
    { word: "curiosity", meaning: "好奇心 n" },
    { word: "laptop", meaning: "笔记本电脑 n" },
    { word: "fear", meaning: "害怕 v n" },
    { word: "failure", meaning: "失败 n" },
    { word: "awful", meaning: "可怕的 adj" },
    { word: "medical", meaning: "医疗的 adj" },
    { word: "belong to", meaning: "属于" },
    { word: "certain", meaning: "某个；确信的 adj" },
    { word: "analyze", meaning: "分析 v" },
    { word: "upset", meaning: "沮丧的 adj" },
    { word: "relate to", meaning: "涉及，关系到" },
    { word: "address", meaning: "地址 n；处理、回应（问题）v" },
  ]},
  { id: 19, name: "第19组", words: [
    { word: "constantly", meaning: "不断地 adv" },
    { word: "pretend", meaning: "假装 v" },
    { word: "in advance", meaning: "提前" },
    { word: "make promise", meaning: "做出承诺" },
    { word: "face", meaning: "面对 v" },
    { word: "performance", meaning: "表演，表现 n" },
    { word: "hobby", meaning: "爱好 n" },
    { word: "energetic", meaning: "充满活力的 adj" },
    { word: "source", meaning: "来源 n" },
    { word: "truthful", meaning: "真诚的" },
    { word: "balloon", meaning: "气球 n" },
    { word: "screen", meaning: "屏幕 n" },
    { word: "disadvantage", meaning: "缺点 n" },
    { word: "preference", meaning: "偏好，偏爱，喜好 n" },
    { word: "regular", meaning: "规律的 adj" },
    { word: "method", meaning: "方法 n" },
    { word: "society", meaning: "社会 n" },
    { word: "analysis", meaning: "分析 n" },
    { word: "weight", meaning: "重量 n." },
    { word: "detail", meaning: "细节 n" },
  ]},
  { id: 20, name: "第20组", words: [
    { word: "set up", meaning: "创建，建立" },
    { word: "physically", meaning: "物理上地；身体上地 v" },
    { word: "liberate", meaning: "解放 v" },
    { word: "be of medium height", meaning: "中等身高" },
    { word: "advantage", meaning: "优点 n" },
    { word: "package", meaning: "包裹、打包 v n" },
    { word: "determination", meaning: "决心 n" },
    { word: "effect", meaning: "效果，影响 n" },
    { word: "overreact", meaning: "过激反应 v" },
    { word: "debt", meaning: "债务 n" },
    { word: "bright", meaning: "明亮的，光明的 adj" },
    { word: "make a difference", meaning: "做出改变、取得一定成就" },
    { word: "challenge", meaning: "挑战 v n" },
    { word: "evidence", meaning: "证据 n" },
    { word: "proper", meaning: "恰当的 adj" },
    { word: "beg pardon", meaning: "请求原谅" },
    { word: "rush", meaning: "冲撞 v" },
    { word: "match", meaning: "匹配 v；比赛，火柴 n" },
    { word: "regret", meaning: "后悔 v" },
    { word: "blue", meaning: "抑郁的 adj" },
  ]},
  { id: 21, name: "第21组", words: [
    { word: "suggest", meaning: "建议、暗示 v" },
    { word: "attractive", meaning: "有吸引力的 adj" },
    { word: "benefit", meaning: "益处、好处 n" },
    { word: "remove", meaning: "移走，移除 v" },
    { word: "rarely", meaning: "罕见地，很少 adv" },
    { word: "interaction", meaning: "互动 n" },
    { word: "as soon as", meaning: "一…就 …" },
    { word: "mass", meaning: "大规模 n" },
    { word: "courage", meaning: "勇气 n" },
    { word: "send", meaning: "寄，发送 v" },
    { word: "complete", meaning: "完成 v；完整的 adj" },
    { word: "list", meaning: "名单、清单 n" },
    { word: "fiction", meaning: "科幻 n" },
    { word: "necessarily", meaning: "必然地，必要地 adv" },
    { word: "stand", meaning: "站台 n；忍受 v" },
    { word: "equal", meaning: "平等的" },
    { word: "refuse", meaning: "拒绝 v" },
    { word: "disappointed", meaning: "失望的 adj" },
    { word: "map", meaning: "绘制地图 v；地图 n" },
    { word: "translate", meaning: "翻译 v" },
  ]},
  { id: 22, name: "第22组", words: [
    { word: "due to", meaning: "由于" },
    { word: "sheet", meaning: "床单、纸张 n" },
    { word: "exist", meaning: "存在，生存 v" },
    { word: "adventure", meaning: "冒险 n" },
    { word: "location", meaning: "位置 n" },
    { word: "without", meaning: "没有 prep" },
    { word: "optimistic", meaning: "乐观的 adj" },
    { word: "build character", meaning: "磨炼意志" },
    { word: "rescue", meaning: "营救、解救 v n" },
    { word: "arrange", meaning: "安排 n" },
    { word: "fake", meaning: "假的 adj，假货 n" },
    { word: "head", meaning: "朝着 v head to" },
    { word: "progress", meaning: "进步，进展 n" },
    { word: "painful", meaning: "疼痛的 adj" },
    { word: "community", meaning: "社区 n" },
    { word: "unbearable", meaning: "无法容忍的 adj" },
    { word: "send for the doctor", meaning: "派人去找(医生)..." },
    { word: "contact", meaning: "联系 v" },
    { word: "behave", meaning: "行为 v." },
    { word: "dependent", meaning: "依赖的 adj" },
  ]},
  { id: 23, name: "第23组", words: [
    { word: "relatively", meaning: "相对地 adv" },
    { word: "suffer", meaning: "遭受 v" },
    { word: "switch off", meaning: "关上（turn off）" },
    { word: "print", meaning: "打印 v" },
    { word: "presence", meaning: "存在 n" },
    { word: "state", meaning: "陈述 v；状态 n" },
    { word: "mend", meaning: "修理 v" },
    { word: "mindful", meaning: "留心的，警觉的 adj" },
    { word: "cause", meaning: "引起 v；原因 n" },
    { word: "feel like doing sth", meaning: "喜欢做某事" },
    { word: "environment", meaning: "环境 n" },
    { word: "update", meaning: "更新 v" },
    { word: "own", meaning: "自己的 adj；拥有 v" },
    { word: "reach", meaning: "到达；够得着 v" },
    { word: "misunderstand", meaning: "错误理解 v" },
    { word: "run out of", meaning: "用光" },
    { word: "disappointment", meaning: "失望 n" },
    { word: "decide to do sth", meaning: "决定做某事" },
    { word: "check in", meaning: "报到，登记" },
    { word: "reliable", meaning: "可靠的 adj" },
  ]},
  { id: 24, name: "第24组", words: [
    { word: "rude", meaning: "粗鲁的 adj" },
    { word: "escape", meaning: "逃脱 v" },
    { word: "tie", meaning: "领带 n 绑 v" },
    { word: "solution", meaning: "解决办法 n" },
    { word: "media", meaning: "媒体 n" },
    { word: "EQ ( emotional )", meaning: "情商" },
    { word: "immediately", meaning: "立刻=at once<br>马上 adv" },
    { word: "be willing to do", meaning: "愿意做某事" },
    { word: "attitude", meaning: "态度 n" },
    { word: "speechless", meaning: "无言以对的 adj" },
    { word: "mix", meaning: "混合 v" },
    { word: "blame", meaning: "把…归咎于 v" },
    { word: "balance", meaning: "平衡 v n" },
    { word: "complain", meaning: "抱怨 v" },
    { word: "present", meaning: "礼物 n；现在的 adj；<br>呈现、呈给某人 v" },
    { word: "require", meaning: "需求，要求 v" },
    { word: "switch on", meaning: "打开（turn on）" },
    { word: "shortcut", meaning: "捷径 n" },
    { word: "audience", meaning: "观众 n" },
    { word: "displease", meaning: "使生气，不高兴 v" },
  ]},
  { id: 25, name: "第25组", words: [
    { word: "be determined to do sth", meaning: "决定做某事" },
    { word: "bully", meaning: "欺负 霸凌 v" },
    { word: "deadliest", meaning: "最致命的（deadly是原级）adj" },
    { word: "achieve", meaning: "达到，成功 v" },
    { word: "over and over again", meaning: "一次又一次" },
    { word: "unfair", meaning: "不公平的 adj" },
    { word: "uncontrollable", meaning: "无法控制的 adj" },
    { word: "effective", meaning: "有效果的 adj" },
    { word: "average", meaning: "平均 adj n" },
    { word: "competition", meaning: "比赛 n" },
    { word: "judge", meaning: "判断 v；裁判员、法官 n." },
    { word: "major", meaning: "主要的 adj 专业 n" },
    { word: "take care of", meaning: "照顾=look after" },
    { word: "technology", meaning: "科技 n" },
    { word: "honest", meaning: "诚实的 adj" },
    { word: "rather than", meaning: "而不是" },
    { word: "sight", meaning: "视线 n" },
    { word: "blow", meaning: "吹 v" },
    { word: "result", meaning: "结果 n" },
    { word: "brain", meaning: "大脑 n" },
  ]},
  { id: 26, name: "第26组", words: [
    { word: "pride", meaning: "骄傲 n" },
    { word: "interactive", meaning: "互动的 adj" },
    { word: "seem", meaning: "似乎 v" },
    { word: "popular", meaning: "受欢迎的 adj" },
    { word: "continually", meaning: "不断地 adv" },
    { word: "fewer", meaning: "更少（否定含义）adj" },
    { word: "decrease", meaning: "减少 v" },
    { word: "population", meaning: "人口 n" },
    { word: "afford", meaning: "支付得起 v" },
    { word: "pleasant", meaning: "愉快的 adj" },
    { word: "pronounce", meaning: "发音 v" },
    { word: "dialogue", meaning: "对话 v" },
    { word: "weigh", meaning: "权衡，称重 v." },
    { word: "quiet", meaning: "安静的 adj" },
    { word: "take over", meaning: "接手" },
    { word: "aim", meaning: "目标 n" },
    { word: "affect", meaning: "影响 v" },
    { word: "deliver", meaning: "传递，递给 v" },
    { word: "unpleasant", meaning: "不愉快的 adj" },
    { word: "plan", meaning: "计划 v n" },
  ]},
  { id: 27, name: "第27组", words: [
    { word: "reward", meaning: "回报、报答 v<br>n" },
    { word: "unlike", meaning: "不像 prep" },
    { word: "break", meaning: "休息 n；打破 v" },
    { word: "work", meaning: "起作用 v；作品 n" },
    { word: "eager", meaning: "渴望的、乐意的 adj" },
    { word: "relaxed", meaning: "放松的 adj" },
    { word: "warn", meaning: "警告，提醒 v n" },
    { word: "event", meaning: "事件 n" },
    { word: "point to", meaning: "指向" },
    { word: "argue", meaning: "争辩，争论，说 v" },
    { word: "place", meaning: "放置 v；地方 n" },
    { word: "attentive", meaning: "注意力集中的 adj" },
    { word: "medium", meaning: "中等的，中号的 adj" },
    { word: "deadline", meaning: "截止日期 n" },
    { word: "insist", meaning: "坚持 v" },
    { word: "track", meaning: "跟踪 v，轨道 n" },
    { word: "unexpectedly", meaning: "意料之外地 adv" },
    { word: "on purpose", meaning: "故意" },
    { word: "absent", meaning: "缺席的" },
    { word: "able", meaning: "能够的" },
  ]},
  { id: 28, name: "第28组", words: [
    { word: "disable", meaning: "残疾" },
    { word: "avoid", meaning: "避免避开" },
    { word: "basic", meaning: "基本的" },
    { word: "actual", meaning: "实际的" },
    { word: "according", meaning: "根据" },
    { word: "admire", meaning: "欣赏羡慕钦佩" },
    { word: "adult", meaning: "成年人" },
    { word: "agreeable", meaning: "令人愉快的;宜人的" },
    { word: "block", meaning: "街区；阻挡；木块" },
    { word: "disagree", meaning: "不同意" },
    { word: "board", meaning: "登；宣传栏" },
    { word: "bore sb", meaning: "使无聊" },
    { word: "compare", meaning: "对比" },
    { word: "company", meaning: "陪伴" },
    { word: "confident", meaning: "自信的" },
    { word: "capital", meaning: "首都，资本" },
    { word: "carry on", meaning: "继续" },
    { word: "congratulate", meaning: "庆祝，为…感到自豪" },
    { word: "course", meaning: "课程，过程，一道菜" },
    { word: "celebrate", meaning: "庆祝" },
  ]},
  { id: 29, name: "第29组", words: [
    { word: "continue", meaning: "继续-continuous" },
    { word: "count", meaning: "数数；重要" },
    { word: "choice", meaning: "选择" },
    { word: "critics", meaning: "批评者" },
    { word: "collect", meaning: "收集，接，镇定（oneself）" },
    { word: "creative thinking", meaning: "创意思维/ critical thinking 批判思" },
    { word: "come down to", meaning: "归结于" },
    { word: "when it comes to", meaning: "当谈到" },
    { word: "communicate", meaning: "交流" },
    { word: "nerve", meaning: "神经" },
    { word: "normal", meaning: "正常的" },
    { word: "organize", meaning: "组织" },
    { word: "meaningful", meaning: "有意义的" },
    { word: "pain", meaning: "痛" },
    { word: "passage", meaning: "文章，通道" },
    { word: "memory", meaning: "记忆" },
    { word: "patient", meaning: "耐心的；病人" },
    { word: "perform", meaning: "表现表演" },
    { word: "in person", meaning: "亲自" },
    { word: "productive", meaning: "多产的" },
  ]},
  { id: 30, name: "第30组", words: [
    { word: "plenty of", meaning: "许多" },
    { word: "private", meaning: "私人的" },
    { word: "predict", meaning: "预测" },
    { word: "primary", meaning: "初级的，首要的" },
    { word: "prefer", meaning: "更喜欢" },
    { word: "reality", meaning: "现实" },
    { word: "describe", meaning: "描述" },
    { word: "design a poster", meaning: "设计海报" },
    { word: "develop", meaning: "发展，增进等" },
    { word: "differ from", meaning: "不同于" },
    { word: "be divided into", meaning: "被分成" },
    { word: "during", meaning: "在…期间" },
    { word: "technology-driven", meaning: "科技驱动的" },
    { word: "be eager to", meaning: "渴望" },
    { word: "ease the pain", meaning: "缓解疼痛" },
    { word: "feel uneasy", meaning: "不安" },
    { word: "education", meaning: "教育" },
    { word: "electronic device", meaning: "电子设备" },
    { word: "emotion", meaning: "情绪" },
    { word: "enemy", meaning: "敌人" },
  ]},
  { id: 31, name: "第31组", words: [
    { word: "energy", meaning: "能量能源" },
    { word: "engineer", meaning: "工程师" },
    { word: "especially", meaning: "尤其" },
    { word: "expect", meaning: "期待" },
    { word: "except", meaning: "除了" },
    { word: "exceptional", meaning: "杰出的，卓越的;异常的" },
    { word: "express", meaning: "表达" },
    { word: "erase the footprint", meaning: "擦除足迹" },
    { word: "the exact date", meaning: "确切的," },
    { word: "fame", meaning: "名誉" },
    { word: "favor", meaning: "偏爱，喜欢" },
    { word: "feedback", meaning: "反馈" },
    { word: "field trip", meaning: "郊游外出" },
    { word: "fever", meaning: "发烧…" },
    { word: "final", meaning: "最终的" },
    { word: "as follows", meaning: "如下" },
    { word: "frighten", meaning: "使害怕" },
    { word: "foreign", meaning: "国外的，陌生的" },
    { word: "fresh", meaning: "新鲜的" },
    { word: "in general", meaning: "总体上" },
  ]},
  { id: 32, name: "第32组", words: [
    { word: "gentle", meaning: "轻轻的" },
    { word: "glove", meaning: "手套" },
    { word: "goal", meaning: "球门，目标，得分" },
    { word: "government", meaning: "政府" },
    { word: "gradually", meaning: "逐渐" },
    { word: "grammar", meaning: "语法" },
    { word: "greet", meaning: "打招呼" },
    { word: "guard", meaning: "守卫保护" },
    { word: "guide", meaning: "导游，引导，导览" },
    { word: "form the habit of", meaning: "形成习惯" },
    { word: "harmless", meaning: "无害的" },
    { word: "heat", meaning: "加热，热" },
    { word: "height", meaning: "高度" },
    { word: "hidden", meaning: "隐藏的" },
    { word: "hunger", meaning: "饥饿" },
    { word: "imagine", meaning: "想象" },
    { word: "immediate", meaning: "立即的" },
    { word: "increasingly popular", meaning: "越来越流行" },
    { word: "industry", meaning: "工业行业" },
    { word: "infer", meaning: "推断" },
  ]},
  { id: 33, name: "第33组", words: [
    { word: "have a great influence on", meaning: "影响" },
    { word: "inform sb of sth", meaning: "通知，告知" },
    { word: "instruction", meaning: "指导说明" },
    { word: "instrument", meaning: "乐器" },
    { word: "interrupt", meaning: "打断谈话，使中断" },
    { word: "interview", meaning: "面试" },
    { word: "introduce", meaning: "介绍；引进" },
    { word: "invite", meaning: "邀请，招致 招致 &" },
    { word: "be involved in", meaning: "参与涉及" },
    { word: "keyboard", meaning: "键盘" },
    { word: "knowledge", meaning: "知识；知道" },
    { word: "laughter", meaning: "笑" },
    { word: "limited", meaning: "有限的" },
    { word: "litter", meaning: "垃圾；扔垃圾" },
    { word: "long-lasting", meaning: "持久的" },
    { word: "lay the groundwork for", meaning: "奠定基础" },
    { word: "enlarge", meaning: "扩大" },
    { word: "misleading", meaning: "误导的" },
    { word: "reasonable", meaning: "合理的" },
    { word: "regardless of", meaning: "尽管不管" },
  ]},
  { id: 34, name: "第34组", words: [
    { word: "relate", meaning: "关联" },
    { word: "relative-ly", meaning: "相对来说" },
    { word: "remain silent", meaning: "保持沉默" },
    { word: "remind sb of sth", meaning: "提醒，使想起" },
    { word: "repeat", meaning: "重复" },
    { word: "respect", meaning: "尊重" },
    { word: "result in", meaning: "导致引起" },
    { word: "time-saving", meaning: "省时的" },
    { word: "satisfy", meaning: "满足" },
    { word: "score", meaning: "分数，得分" },
    { word: "search for", meaning: "搜索" },
    { word: "seldom", meaning: "几乎不" },
    { word: "sense of responsibility", meaning: "责任感" },
    { word: "separate", meaning: "分开" },
    { word: "serious", meaning: "严肃认真的；严重的" },
    { word: "serve", meaning: "服务；上菜；服役" },
    { word: "several", meaning: "几个" },
    { word: "shame", meaning: "羞愧" },
    { word: "in sight", meaning: "视线内 视线内&" },
    { word: "sign language", meaning: "手语" },
  ]},
  { id: 35, name: "第35组", words: [
    { word: "silent-silence", meaning: "沉默" },
    { word: "simple", meaning: "简单的" },
    { word: "single out", meaning: "单挑出" },
    { word: "socialize with", meaning: "社交 =connect" },
    { word: "spare no efforts", meaning: "不遗余力" },
    { word: "spread", meaning: "传播；伸展" },
    { word: "square", meaning: "广场；平方" },
    { word: "steal", meaning: "偷-stolen" },
    { word: "stepping stone", meaning: "奠基石" },
    { word: "straight", meaning: "直的，直接" },
    { word: "reduce stress", meaning: "减压" },
    { word: "stress the importance of", meaning: "强调重要" },
    { word: "stress out", meaning: "压力很大" },
    { word: "be strict with", meaning: "严格" },
    { word: "subject", meaning: "科目；受试者；课程" },
    { word: "succeed success", meaning: "成功" },
    { word: "supply", meaning: "供应" },
    { word: "support", meaning: "支持支撑" },
    { word: "surface", meaning: "表面；浮出表面" },
    { word: "according to the survey", meaning: "据调查" },
  ]},
  { id: 36, name: "第36组", words: [
    { word: "system", meaning: "系统" },
    { word: "symbol", meaning: "象征" },
    { word: "talent", meaning: "天赋" },
    { word: "temperature", meaning: "温度" },
    { word: "in terms of", meaning: "就…而言" },
    { word: "lead in the topic", meaning: "导入话题" },
    { word: "in total", meaning: "总的来说" },
    { word: "tourism", meaning: "旅游业" },
    { word: "trade", meaning: "贸易；交换" },
    { word: "treat", meaning: "对待款待；治疗治理" },
    { word: "typical", meaning: "典型" },
    { word: "vary", meaning: "变化" },
    { word: "volunteer", meaning: "志愿者；志愿做" },
    { word: "warn warning", meaning: "警告" },
    { word: "wealth", meaning: "财富" },
    { word: "weigh A against B", meaning: "衡量" },
    { word: "lose weight", meaning: "减肥" },
    { word: "whole-heartedly", meaning: "全心全意" },
    { word: "wonder why", meaning: "想知道" },
    { word: "worth", meaning: "价值" },
  ]},
];

export const TOTAL_GROUPS = VOCAB_GROUPS.length;
