/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as CoachLoginRouteImport } from './routes/coach.login'
import { Route as PracticeGroupIdModeRouteImport } from './routes/practice.$groupId.$mode'
import { Route as ApiPublicNotifySalesRouteImport } from './routes/api.public.notify-sales'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const CoachLoginRoute = CoachLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CoachRoute,
} as any)
const PracticeGroupIdModeRoute = PracticeGroupIdModeRouteImport.update({
  id: '/$groupId/$mode',
  path: '/$groupId/$mode',
  getParentRoute: () => PracticeRoute,
} as any)
const ApiPublicNotifySalesRoute = ApiPublicNotifySalesRouteImport.update({
  id: '/api/public/notify-sales',
  path: '/api/public/notify-sales',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/coach': typeof CoachRouteWithChildren
  '/coaches': typeof CoachesRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/practice': typeof PracticeRouteWithChildren
  '/ranking': typeof RankingRoute
  '/coach/login': typeof CoachLoginRoute
  '/practice/': typeof PracticeIndexRoute
  '/api/public/notify-sales': typeof ApiPublicNotifySalesRoute
  '/practice/$groupId/$mode': typeof PracticeGroupIdModeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/coach': typeof CoachRouteWithChildren
  '/coaches': typeof CoachesRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/ranking': typeof RankingRoute
  '/coach/login': typeof CoachLoginRoute
  '/practice': typeof PracticeIndexRoute
  '/api/public/notify-sales': typeof ApiPublicNotifySalesRoute
  '/practice/$groupId/$mode': typeof PracticeGroupIdModeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/coach': typeof CoachRouteWithChildren
  '/coaches': typeof CoachesRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/practice': typeof PracticeRouteWithChildren
  '/ranking': typeof RankingRoute
  '/coach/login': typeof CoachLoginRoute
  '/practice/': typeof PracticeIndexRoute
  '/api/public/notify-sales': typeof ApiPublicNotifySalesRoute
  '/practice/$groupId/$mode': typeof PracticeGroupIdModeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/coach'
    | '/coaches'
    | '/dashboard'
    | '/join'
    | '/practice'
    | '/ranking'
    | '/coach/login'
    | '/practice/'
    | '/api/public/notify-sales'
    | '/practice/$groupId/$mode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/coach'
    | '/coaches'
    | '/dashboard'
    | '/join'
    | '/ranking'
    | '/coach/login'
    | '/practice'
    | '/api/public/notify-sales'
    | '/practice/$groupId/$mode'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/coach'
    | '/coaches'
    | '/dashboard'
    | '/join'
    | '/practice'
    | '/ranking'
    | '/coach/login'
    | '/practice/'
    | '/api/public/notify-sales'
    | '/practice/$groupId/$mode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CoachRoute: typeof CoachRouteWithChildren
  CoachesRoute: typeof CoachesRoute
  DashboardRoute: typeof DashboardRoute
  JoinRoute: typeof JoinRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  RankingRoute: typeof RankingRoute
  ApiPublicNotifySalesRoute: typeof ApiPublicNotifySalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/coach/login': {
      id: '/coach/login'
      path: '/login'
      fullPath: '/coach/login'
      preLoaderRoute: typeof CoachLoginRouteImport
      parentRoute: typeof CoachRoute
    }
    '/practice/$groupId/$mode': {
      id: '/practice/$groupId/$mode'
      path: '/$groupId/$mode'
      fullPath: '/practice/$groupId/$mode'
      preLoaderRoute: typeof PracticeGroupIdModeRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/api/public/notify-sales': {
      id: '/api/public/notify-sales'
      path: '/api/public/notify-sales'
      fullPath: '/api/public/notify-sales'
      preLoaderRoute: typeof ApiPublicNotifySalesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoachRouteChildren {
  CoachLoginRoute: typeof CoachLoginRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachLoginRoute: CoachLoginRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

interface PracticeRouteChildren {
  PracticeIndexRoute: typeof PracticeIndexRoute
  PracticeGroupIdModeRoute: typeof PracticeGroupIdModeRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeIndexRoute: PracticeIndexRoute,
  PracticeGroupIdModeRoute: PracticeGroupIdModeRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CoachRoute: CoachRouteWithChildren,
  CoachesRoute: CoachesRoute,
  DashboardRoute: DashboardRoute,
  JoinRoute: JoinRoute,
  PracticeRoute: PracticeRouteWithChildren,
  RankingRoute: RankingRoute,
  ApiPublicNotifySalesRoute: ApiPublicNotifySalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
