/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeModeRouteImport } from './routes/practice.$mode'

const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeModeRoute = PracticeModeRouteImport.update({
  id: '/$mode',
  path: '/$mode',
  getParentRoute: () => PracticeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coaches': typeof CoachesRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/practice': typeof PracticeRouteWithChildren
  '/ranking': typeof RankingRoute
  '/sales': typeof SalesRoute
  '/practice/$mode': typeof PracticeModeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coaches': typeof CoachesRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/practice': typeof PracticeRouteWithChildren
  '/ranking': typeof RankingRoute
  '/sales': typeof SalesRoute
  '/practice/$mode': typeof PracticeModeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coaches': typeof CoachesRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/practice': typeof PracticeRouteWithChildren
  '/ranking': typeof RankingRoute
  '/sales': typeof SalesRoute
  '/practice/$mode': typeof PracticeModeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coaches'
    | '/dashboard'
    | '/join'
    | '/practice'
    | '/ranking'
    | '/sales'
    | '/practice/$mode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coaches'
    | '/dashboard'
    | '/join'
    | '/practice'
    | '/ranking'
    | '/sales'
    | '/practice/$mode'
  id:
    | '__root__'
    | '/'
    | '/coaches'
    | '/dashboard'
    | '/join'
    | '/practice'
    | '/ranking'
    | '/sales'
    | '/practice/$mode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachesRoute: typeof CoachesRoute
  DashboardRoute: typeof DashboardRoute
  JoinRoute: typeof JoinRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  RankingRoute: typeof RankingRoute
  SalesRoute: typeof SalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$mode': {
      id: '/practice/$mode'
      path: '/$mode'
      fullPath: '/practice/$mode'
      preLoaderRoute: typeof PracticeModeRouteImport
      parentRoute: typeof PracticeRoute
    }
  }
}

interface PracticeRouteChildren {
  PracticeModeRoute: typeof PracticeModeRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeModeRoute: PracticeModeRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachesRoute: CoachesRoute,
  DashboardRoute: DashboardRoute,
  JoinRoute: JoinRoute,
  PracticeRoute: PracticeRouteWithChildren,
  RankingRoute: RankingRoute,
  SalesRoute: SalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
